### PR TITLE
Create checkov.yml

### PR DESCRIPTION
**Pull request by the-tatanka**

### CODE REVIEW

**Comment by the-tatanka** [comment]
Mandatory workflow - please merge immediately.

**Comment by mkanal** [comment]
Push image failes with error message: 
PR denied: installation not allowed to Write organization package
Error: Process completed with exit code 1.

**Comment by the-tatanka** [comment]
Checkov has no influence on your code and build!
It's just an action that runs over the main branch once at night.

**Comment by the-tatanka** [comment]
Which means that something is "probably" wrong with the build - not with the action.
Please merge the action.

**Comment by ds-jkreutzfeld** [comment]
Image pushes in PRs from forked repositories are not allowed using the GITHUB_TOKEN (see https://github.community/t/cant-authenticate-with-actions-token-for-pr-event/170752).
That's why the workflow fails.
I will override the requirements here and merge it anyway.

**Pull request merged**
